// Generated by scripts/generateSchemaIndex.js. Do not edit by hand.
export * from "../../features/authors/authors.db.js";
export * from "../../features/blogs/blogs.db.js";
export * from "../../features/careers/careers.db.js";
export * from "../../features/classes/classes.db.js";
export * from "../../features/contact/contact.db.js";
export * from "../../features/countries/countries.db.js";
export * from "../../features/events/events.db.js";
export * from "../../features/jobs/jobs.db.js";
export * from "../../features/media/media.db.js";
export * from "../../features/notices/notices.db.js";
export * from "../../features/partners/partners.db.js";
export * from "../../features/registrations/registrations.db.js";
export * from "../../features/students/students.db.js";
export * from "../../features/successProfiles/successProfiles.db.js";
export * from "../../features/users/users.db.js";
export * from "../../features/visitors/visitors.db.js";
