import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const featuresDirectory = path.join(projectRoot, "features");
const outputFile = path.join(projectRoot, "db", "schema", "index.js");

const exports = fs
  .readdirSync(featuresDirectory, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .flatMap((entry) => {
    const directory = path.join(featuresDirectory, entry.name);
    return fs
      .readdirSync(directory, { withFileTypes: true })
      .filter((file) => file.isFile() && file.name.endsWith(".db.js"))
      .map((file) => `export * from "../../features/${entry.name}/${file.name}";`);
  })
  .sort();

const contents = [
  "// Generated by scripts/generateSchemaIndex.js. Do not edit by hand.",
  ...exports,
  "",
].join("\n");

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, contents, "utf8");
console.log(`Generated ${path.relative(projectRoot, outputFile)} with ${exports.length} modules`);
